// app/api/guardian/students/route.ts
// Purpose: Create a new student profile (Case 1 — no match found)
// Who can call it: authenticated GUARDIAN with complete profile

import { createClient } from "@/lib/supabase/server"
import { createAdminClient } from "@/lib/supabase/admin"
import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import { normalizeName, normalizeDob } from "@/lib/utils/normalize"
import { isGuardianProfileComplete } from "@/lib/utils/guardian"
import { dobSchema, genderSchema } from "@/lib/validations/common"
import { writeAuditLog } from "@/lib/utils/audit"

const createStudentSchema = z.object({
  fullName: z.string().min(2).max(100).trim(),
  dateOfBirth: dobSchema,
  gender: genderSchema,
  confirmedNoMatch: z.boolean(),
})

export async function POST(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const adminClient = createAdminClient()
  const { data: userData } = await adminClient
    .from("users")
    .select("role")
    .eq("id", user.id)
    .single()

  if (!userData || userData.role !== "GUARDIAN") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const profileComplete = await isGuardianProfileComplete(user.id)
  if (!profileComplete) {
    return NextResponse.json(
      { error: "Complete your profile before adding students" },
      { status: 403 }
    )
  }

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 })
  }

  const result = createStudentSchema.safeParse(body)
  if (!result.success) {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 })
  }

  const { fullName, dateOfBirth, gender, confirmedNoMatch } = result.data

  if (!confirmedNoMatch) {
    return NextResponse.json(
      { error: "Must confirm no matching student was found" },
      { status: 400 }
    )
  }

  const nameNormalized = normalizeName(fullName)
  const dobNormalized = normalizeDob(dateOfBirth)

  // Run one final duplicate check before creating
  const { data: finalCheck } = await adminClient.rpc(
    "search_students_fuzzy",
    {
      p_name_normalized: nameNormalized,
      p_dob_normalized: dobNormalized,
      p_similarity_threshold: 0.85,
    }
  )

  // Block creation if a HIGH confidence match exists
  if (finalCheck && finalCheck.length > 0) {
    const topMatch = finalCheck[0]
    if (topMatch && topMatch.overall_score >= 0.9) {
      return NextResponse.json(
        {
          error:
            "A very similar student record was found. Please review it before creating a new profile.",
          match: {
            stuId: topMatch.stu_id,
            fullName: topMatch.full_name,
            dateOfBirth: topMatch.date_of_birth,
          },
        },
        { status: 409 }
      )
    }
  }

  // Create student — STU ID auto-generated by sequence DEFAULT
  const { data: newStudent, error: createError } = await adminClient
    .from("students")
    .insert({
      full_name: fullName,
      full_name_normalized: nameNormalized,
      date_of_birth: dateOfBirth,
      dob_normalized: dobNormalized,
      gender,
      status: "ACTIVE",
    })
    .select("id, stu_id, full_name, date_of_birth, gender")
    .single()

  if (createError || !newStudent) {
    return NextResponse.json(
      { error: "Could not create student profile" },
      { status: 500 }
    )
  }

  // Link student to guardian as PRIMARY
  const { error: linkError } = await adminClient
    .from("guardian_student_links")
    .insert({
      guardian_id: user.id,
      student_id: newStudent.id,
      link_type: "PRIMARY",
      is_active: true,
    })

  if (linkError) {
    // Roll back student creation if link fails
    await adminClient
      .from("students")
      .delete()
      .eq("id", newStudent.id)

    return NextResponse.json(
      { error: "Could not link student to account" },
      { status: 500 }
    )
  }

  await writeAuditLog({
    actorId: user.id,
    actorRole: "GUARDIAN",
    actionType: "STUDENT_CREATED",
    targetTable: "students",
    targetId: newStudent.id,
    newValue: {
      stu_id: newStudent.stu_id,
      full_name: fullName,
      date_of_birth: dateOfBirth,
      gender,
    },
  })

  return NextResponse.json({ student: newStudent })
}

// GET — list all students linked to this guardian
export async function GET(request: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const adminClient = createAdminClient()
  const { data: userData } = await adminClient
    .from("users")
    .select("role")
    .eq("id", user.id)
    .single()

  if (!userData || userData.role !== "GUARDIAN") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const { data: links, error } = await adminClient
    .from("guardian_student_links")
    .select(`
      id,
      link_type,
      is_active,
      students!inner (
        id,
        stu_id,
        full_name,
        date_of_birth,
        gender,
        status
      )
    `)
    .eq("guardian_id", user.id)
    .eq("is_active", true)
    .order("created_at", { ascending: true })

  if (error) {
    return NextResponse.json(
      { error: "Could not fetch students" },
      { status: 500 }
    )
  }

  return NextResponse.json({ students: links ?? [] })
}